name: Build and Run Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build Docker Image
      run: docker build -t mypythonapp .

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: taslimalmunawiy10
        password: dckr_pat_n_iXKc_nA5xooDLlvHRgVTn7xmM 

    - name: Push to Docker Hub
      run:
        docker tag mypythonapp taslimalmunawiy10/mypythonapp:latest
        docker push taslimalmunawiy10/mypythonapp:latest
